Make psutil reloadable on linux
For safety reasons, reloading a module does not reinitialize c
extensions. For this reason, `del <c_extension>` in `__init__.py`
yields the following on reimport:

```
Traceback (most recent call last):
  File "/src/test/_linux.py", line 479, in test_psutil_is_reloadable
    imp.reload(psutil)
  File "psutil/__init__.py", line 89, in <module>
    from . import _psutil_linux
ImportError: cannot import name _psutil_linux
```

As none of the other platform-specific extensions are removed from
the module dict post-import, we simply omit the `del` for linux.