OpenBSD is unable to recognize zombie process. See failure:
======================================================================
ERROR: psutil.tests.test_process.TestProcess.test_zombie_process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/psutil/psutil/_psbsd.py", line 560, in wrapper
    return fun(self, *args, **kwargs)
  File "/vagrant/psutil/psutil/_psbsd.py", line 862, in open_files
    rawlist = cext.proc_open_files(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/psutil/psutil/tests/test_process.py", line 1312, in test_zombie_process
    zproc.as_dict()
  File "/vagrant/psutil/psutil/__init__.py", line 528, in as_dict
    ret = meth()
  File "/vagrant/psutil/psutil/__init__.py", line 1142, in open_files
    return self._proc.open_files()
  File "/vagrant/psutil/psutil/_psbsd.py", line 565, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=67013)

----------------------------------------------------------------------
Ran 1 test in 0.136s

FAILED (errors=1)