IMPORTANT: much shorter traceback on Process.__init__.
When passing a non existent PID to Process(), we now get a very compact traceback:

    ```
    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
        p = psutil.Process(123124)
            ^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
        self._init(pid)
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 363, in _init
        raise NoSuchProcess(pid, msg=msg) from None
    psutil.NoSuchProcess: process PID not found (pid=123124)
    ```

Before we got:

```
    <traceback object at 0x74d0dd6ddb40>
    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 327, in _init
        _psplatform.cext.check_pid_range(pid)
    OverflowError: Python int too large to convert to C long

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
        p = psutil.Process(132798127392783333912839812793)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
        self._init(pid)
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 332, in _init
        raise NoSuchProcess(pid, msg=msg).with_traceback(tb)
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 327, in _init
        _psplatform.cext.check_pid_range(pid)
    psutil.NoSuchProcess: process PID out of range (pid=132798127392783333912839812793)
    ~/svn/psutil {raise-from}$ ^C
    ~/svn/psutil {raise-from}$ ^C
    ~/svn/psutil {raise-from}$ python3 foo.py
    <traceback object at 0x7ef45b787800>
    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 327, in _init
        _psplatform.cext.check_pid_range(pid)
    OverflowError: Python int too large to convert to C long

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
        p = psutil.Process(132798127392783333912839812793)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
        self._init(pid)
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 332, in _init
        raise NoSuchProcess(pid, msg=msg) from e
    psutil.NoSuchProcess: process PID out of range (pid=132798127392783333912839812793)
    ~/svn/psutil {raise-from}$ ^C
    ~/svn/psutil {raise-from}$ python3 foo.py
    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1647, in wrapper
        return fun(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_common.py", line 464, in wrapper
        raise err from None
      File "/home/giampaolo/svn/psutil/psutil/_common.py", line 462, in wrapper
        return fun(self)
               ^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1713, in _parse_stat_file
        data = bcat(f"{self._procfs_path}/{self.pid}/stat")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_common.py", line 794, in bcat
        return cat(fname, fallback=fallback, _open=open_binary)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_common.py", line 782, in cat
        with _open(fname) as f:
             ^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_common.py", line 746, in open_binary
        return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/proc/123124/stat'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 350, in _init
        self._ident = self._get_ident()
                      ^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 391, in _get_ident
        return (self.pid, self.create_time())
                          ^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 773, in create_time
        self._create_time = self._proc.create_time()
                            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1647, in wrapper
        return fun(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1885, in create_time
        ctime = float(self._parse_stat_file()['create_time'])
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1659, in wrapper
        raise NoSuchProcess(self.pid, self._name)
    psutil.NoSuchProcess: process no longer exists (pid=123124)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
        p = psutil.Process(123124)
            ^^^^^^^^^^^^^^^^^^^^^^
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
        self._init(pid)
      File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 363, in _init
        raise NoSuchProcess(pid, msg=msg)
    psutil.NoSuchProcess: process PID not found (pid=123124)
```