linux: handle missing /sys/class/power_supply in sensors_battery()
The test `TestModuleFunctionsLeaks.test_sensors_battery` fails on Ubuntu
s390x in `sensors_battery` with:

```
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'
```

Fix `sensors_battery` to return `None` in case `POWER_SUPPLY_PATH` does
not exist.

Fixes: https://github.com/giampaolo/psutil/issues/2067
Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>