Fix pre-commit hook for python 3.x.
sh() return value is a string due to Popen(universal_newlines=True).

Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 118, in <module>
    main()
  File ".git/hooks/pre-commit", line 78, in main
    py_files = [x for x in out.split(b'\n') if x.endswith(b'.py') and
TypeError: must be str or None, not bytes