Include net/if.h before net/if_dl.h
In old versions of macOS, net/if_dl.h neglects to include sys/types.h,
which results in build failure:

error: unknown type name 'u_char'; did you mean 'char'?

Including net/if.h first works around the problem because net/if.h
includes sys/types.h.

Fixes #2360