Improved exceptions (`raise from ...`) (#2487)
As part of the dropping of Python 2.7 support (#2480), we can now take advantage of chained exceptions machinery (`raise x from y` and `raise x from None`). In practical terms, this is what changes:

# Shorter tracebacks

When adding the full traceback info adds no value, we now shorten tracebacks if `raise X from None`.
A similar (hackish) attempt was made in https://github.com/giampaolo/psutil/commit/633d8019, when we were still stuck with Python 2. The notable example is passing a PID that does not exist to the `Process` class:

```python
psutil.Process(333)
```

Before we got:

```
Traceback (most recent call last):
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1647, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 464, in wrapper
    raise err from None
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 462, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1713, in _parse_stat_file
    data = bcat(f"{self._procfs_path}/{self.pid}/stat")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 794, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 782, in cat
    with _open(fname) as f:
         ^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 746, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/341244/stat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 350, in _init
    self._ident = self._get_ident()
                  ^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 391, in _get_ident
    return (self.pid, self.create_time())
                      ^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 773, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1647, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1885, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1659, in wrapper
    raise NoSuchProcess(pid, name) from err
psutil.NoSuchProcess: process no longer exists (pid=341244)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
    psutil.Process(341244)
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg)
psutil.NoSuchProcess: process PID not found (pid=341244)
```

Now we get:

```
Traceback (most recent call last):
  File "/home/giampaolo/svn/psutil/foo.py", line 5, in <module>
    psutil.Process(341244)
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=341244)
```

# Different wording for "translated" exceptions

By "translated" I mean psutil's `NoSuchProcess`, `ZombieProcess` and `AccessDenied`.
Given the following code:

```python
import psutil
from psutil.tests import spawn_testproc

sproc = spawn_testproc()
p = psutil.Process(sproc.pid)
p.terminate()
p.wait()
p.name()
```

Before we got:

```
Traceback (most recent call last):
  [...]
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 746, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/105496/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [...]
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1659, in wrapper
    raise NoSuchProcess(pid, name)
psutil.NoSuchProcess: process no longer exists (pid=105496)
```

Now we get:

```
Traceback (most recent call last):
  [...]
  File "/home/giampaolo/svn/psutil/psutil/_common.py", line 746, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/105496/stat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...]
  File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1659, in wrapper
    raise NoSuchProcess(pid, name) from None
psutil.NoSuchProcess: process no longer exists (pid=105496)
```

Diff:

```diff
     FileNotFoundError: [Errno 2] No such file or directory: '/proc/105496/stat'
 
-    During handling of the above exception, another exception occurred:
+    The above exception was the direct cause of the following exception:
 
     Traceback (most recent call last):
       [...]
       File "/home/giampaolo/svn/psutil/psutil/_pslinux.py", line 1659, in wrapper
-        raise NoSuchProcess(pid, name)
+        raise NoSuchProcess(pid, name) from None
     psutil.NoSuchProcess: process no longer exists (pid=105496)
```