Sort results in test_cpu_affinity_all_combinations (#1769)
Fix test_cpu_affinity_all_combinations to permit any CPU order
in results.  This fixes test failure due to affinity being reported
out of order:

    ======================================================================
    FAIL: psutil.tests.test_process.TestProcess.test_cpu_affinity_all_combinations
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/psutil/psutil/tests/test_process.py", line 940, in test_cpu_affinity_all_combinations
        self.assertEqual(p.cpu_affinity(), combo)
    AssertionError: Lists differ: [8, 1] != [1, 8]

    First differing element 0:
    8
    1

    - [8, 1]
    + [1, 8]

    ----------------------------------------------------------------------